name: dropper_shop
main: com.piggest.minecraft.bukkit.dropper_shop.Dropper_shop_plugin
api-version: 1.15
version: 0.1.9
author: Pentyum
commands:
  dropper_shop:
    description: Make a dropper shop.
    usage: /<command> make ,to make a dropper shop which sell the item in you main hand.
    permission: dropper_shop.make
    permission-message: You don't have permission
  depository:
    description: commands relate to depository.
    usage: /<command> make ,to make a depository.
    permission: depository.make
    permission-message: You don't have permission
  grinder:
    description: commands relate to grinder.
    usage: /<command> to see grinder info.
    permission: grinder.make
    permission-message: You don't have permission
  adv_furnace:
    description: commands relate to advanced furnace.
    usage: /<command> remove|temp|getmoney.
    permission: adv_furnace.make
    permission-message: You don't have permission
  wrench:
    description: commands relate to wrench.
    usage: /<command> to see the plugin info or /<command> setprice [world] to change price.
    permission: wrench.use
    permission-message: You don't have permission
  exp_saver:
    description: commands relate to exp_saver.
    usage: /<command> remove to remove a exp saver.
    permission: exp_saver.use
    permission-message: You don't have permission
  lottery:
    description: commands relate to lottery pool.
    usage: /<command> possibility to set the possibility of the item in your hand.
    permission: lottery.use
    permission-message: You don't have permission
  sync_realtime:
    description: commands relate to sync_realtime.
    usage: /<command> worldname true or false to set sync_realtime.
    permission: sync_realtime.list
    permission-message: You don't have permission
  teleport_machine:
    description: commands relate to teleport_machine.
    usage: /<command> [set_online_voltage|set_working_voltage|set_freq|set_bandwidth] value
    permission: teleport_machine.use
    permission-message: You don't have permission
  watersheep:
    description: commands relate to watersheep.
    usage: /<command> curse|bless|info
    permission: watersheep.use
    permission-message: You don't have permission
  biome_modify:
    description: commands relate to biome_modify.
    usage: /<command> show_biome_temp|set_biome_temp
    permission: biome_modify.use
    permission-message: You don't have permission
  electric_spawner:
    description: commands relate to electric spawner.
    usage: /<command> charge money
    permission: electric_spawner.use
    permission-message: You don't have permission
  custom_map:
    description: commands relate to custom map.
    usage: /<command> [get_char|get_digital_clock|get_analog_clock|get_cdm|set_cdm|get_image|get_gif|get_qr_code|reload] args
    permission: custom_map.get
    permission-message: You don't have permission
  printer:
    description: commands relate to printer.
    usage: /<command>
    permission: printer.use
    permission-message: You don't have permission
  my_space:
    description: commands relate to my space.
    usage: /<command> cmd args
    permission: my_space.use
    permission-message: You don't have permission
  scb_eco:
    description: commands relate to scoreboard economy.
    usage: /<command> [pay|collect|give|set]
    permission: scb_eco.use
    permission-message: You don't have permission
permissions:
  dropper_shop.*:
    description: Gives access to all dropper shop commands.
    default: op
  dropper_shop.make:
    description: Gives access to make dropper shop.
    default: true
  dropper_shop.changeprice:
    description: Change price dropper shop.
    default: op
  dropper_shop.unexplodable:
    description: Make unexplodable shop.
    default: op
  dropper_shop.remove:
    description: Remove dropper shop.
    default: true
  dropper_shop.remove.others:
    description: Remove others dropper shop.
    default: op
  dropper_shop.get_item:
    description: get a dropper_shop item.
    default: op
  dropper_shop.set_inhabited_time:
    description: set chunk inhabited time.
    default: op
  depository.make:
    description: Make or remove a depository.
    default: true
  depository.use:
    description: Open upgrade gui of a depository.
    default: true
  depository.connect:
    description: Make a reader connect to a depository.
    default: true
  depository.input:
    description: Input itemstack to a depository.
    default: true
  depository.output:
    description: Get itemstack from a depository.
    default: true
  depository.god:
    description: Change info.
    default: op
  grinder.make:
    description: Make or remove a grinder.
    default: true
  grinder.use:
    description: Use grinder.
    default: true
  adv_furnace.make:
    description: Make or remove a advanced furnace.
    default: true
  adv_furnace.use:
    description: Use advanced furnace.
    default: true
  adv_furnace.admin:
    description: Change advanced furnace.
    default: op
  adv_furnace.make_money:
    description: Make money ability.
    default: true
  adv_furnace.get_money:
    description: Get money ability.
    default: true
  wrench.*:
    description: Gives access to all wrench commands
    default: op
  wrench.use:
    description: Gives access to use wrench
    default: true
  wrench.changeprice:
    description: change wrench price
    default: op
  exp_saver.*:
    description: Gives access to all wrench commands
    default: op
  exp_saver.make:
    description: Gives access to make exp_saver
    default: true
  exp_saver.use:
    description: Gives access to use exp_saver
    default: true
  lottery.*:
    description: Gives access to all lottery pool commands.
    default: op
  lottery.make:
    description: Make lottery pool.
    default: true
  lottery.use:
    description: Use lottery pool.
    default: true
  lottery.set:
    description: Set lottery pool.
    default: op
  trees_felling_machine.make:
    description: Make a trees felling machine.
    default: true
  trees_felling_machine.use:
    description: Use trees felling machine.
    default: true
  pigman_switch.use:
    description: Use pigman switch.
    default: true
  pigman_switch.make:
    description: Make pigman switch.
    default: true
  anti_thunder.use:
    description: Use anti thunder.
    default: true
  anti_thunder.make:
    description: Make anti thunder.
    default: true
  sync_realtime.list:
    description: List sync_realtime worlds.
    default: true
  sync_realtime.set:
    description: Set sync_realtime.
    default: op
  teleport_machine.make:
    description: make.
    default: true
  teleport_machine.use:
    description: use.
    default: true
  teleport_machine.search:
    description: Search radio.
    default: true
  teleport_machine.search.debug:
    description: Search radio debug.
    default: op
  teleport_machine.no_consume:
    description: no consume.
    default: op
  watersheep.use:
    description: use.
    default: true
  flying_item.use:
    description: use flying item.
    default: true
  flying_item.set:
    description: set flying item time.
    default: op
  biome_modify.use:
    description: show biome base temp.
    default: true
  biome_modify.set_biome_temp:
    description: set biome base temp.
    default: op
  compressor.make:
    description: Make compressor.
    default: true
  compressor.use:
    description: Use compressor.
    default: true
  electric_spawner.make:
    description: Make electric spawner.
    default: true
  electric_spawner.use:
    description: Use electric spawner.
    default: true
  electric_spawner.set:
    description: Set electric spawner.
    default: op
  custom_map.get:
    description: Get a custom map.
    default: op
  custom_map.damage_locked_map:
    description: Damage a locked custom map.
    default: op
  custom_map.copy:
    description: copy a custom map.
    default: op
  printer.make:
    description: Make printer.
    default: true
  printer.use:
    description: Use printer.
    default: true
  my_space.use:
    description: Use my space.
    default: true
  scb_eco.use:
    description: Use scb eco system.
    default: true
  scb_eco.bal:
    description: Look up the balance.
    default: true
  scb_eco.pay:
    description: Pay money.
    default: true
  scb_eco.give:
    description: Give money.
    default: op
  scb_eco.take:
    description: Take money.
    default: op
  scb_eco.import:
    description: Import money from another economy plugin.
    default: op
depend: [Vault]
softdepend: [ProtocolLib,PlaceholderAPI]